bugs/urls.py
from django.conf.urls import url,include
from .views import all_bugs,add_edit_bug,bug_detail,upvote_bug,add_comment_bugs

urlpatterns = [
    url(r'^$', all_bugs, name='bugs'),
    url(r'^bug_detail/(?P<id>\d+)/$', bug_detail, name='bug_detail'),
    url(r'^edit_bug/(?P<id>\d+)/$', add_edit_bug, name='edit_bug'),
    url(r'^add_bug/$', add_edit_bug, name='add_bug'),
    url(r'^upvote_bug/(?P<id>\d+)/$', upvote_bug, name='upvote_bug'),
    url(r'^add_comment_bugs/(?P<id>\d+)/$',
        add_comment_bugs, name='add_comment_bugs'),
]

features/urls.py
from django.conf.urls import url,include
from .views import all_features,add_edit_feature,feature_detail,upvote_feature,add_comment_features

urlpatterns = [
    url(r'^$', all_features, name='features'),
    url(r'^feature_detail/(?P<id>\d+)/$', feature_detail, name='feature_detail'),
    url(r'^edit_feature/(?P<id>\d+)/$', add_edit_feature, name='edit_feature'),
    url(r'^add_feature/$', add_edit_feature, name='add_feature'),
    
    url(r'^upvote_feature/(?P<id>\d+)/$', upvote_feature, name='upvote_feature'),
    url(r'^add_comment_features/(?P<id>\d+)/$',
        add_comment_features, name='add_comment_features'),
]

unicorntracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as urls_accounts
from features import urls as urls_features
from bugs import urls as urls_bugs
from features.views import all_features
from bugs.views import all_bugs
from cart import urls as urls_cart
from search import urls as urls_search
from search2 import urls as urls_search2
from graphs import urls as urls_graphs
from django.views import static
from .settings import MEDIA_ROOT 
from home.views import index
from checkout import urls as urls_checkout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^accounts/', include(urls_accounts)),
    url(r'^features/', include(urls_features)),
    url(r'^bugs/', include(urls_bugs)),
    url(r'^cart/', include(urls_cart)),
    url(r'^checkout/', include(urls_checkout)),
    url(r'^search/', include(urls_search)),
    url(r'^search2/', include(urls_search2)),
    url(r'^graphs/', include(urls_graphs)),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT})
]

features/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Features(models.Model):
    ToDo = 'To Do'
    Doing = 'Doing'
    Done = 'Done'
    STATUS_CHOICES = ((ToDo, 'To Do'),
                      (Doing, 'Doing'), (Done, 'Done'))

    name = models.CharField(max_length=50, blank=False)
    description = models.TextField(blank=False)
    username = models.ForeignKey(User, default=None)
    created_date = models.DateTimeField(blank=True, default=None, null=True)
    waiting_date = models.DateTimeField(blank=True, default=None, null=True)
    in_progress_date = models.DateTimeField(
        blank=True, default=None, null=True)
    completion_date = models.DateTimeField(blank=True, default=None, null=True)
    views = models.IntegerField(default=0)
    upvotes = models.IntegerField(default=0)
    status = models.CharField(
        max_length=40, choices=STATUS_CHOICES, default=ToDo)
    image = models.ImageField(upload_to='images')    

    def __str__(self):
        return self.name

class UpvoteFeature(models.Model):
    upvoted_feature = models.ForeignKey(Features, default=None)
    user = models.ForeignKey(User, default=None)

    def __str__(self):
        return str(self.user)


class Comments(models.Model):
    feature_ticket = models.ForeignKey(Features, null=True)
    username = models.ForeignKey(User, null=None)
    comment = models.TextField(blank=False)
    created_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.comment

features/forms.py
from django import forms
from .models import Features,Comments


class FeaturesForm(forms.ModelForm):
    class Meta:
        model = Features
        fields = ['name', 'description']
        

class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(
        attrs={'rows': '4', 'cols': '5'}))

    class Meta:
        model = Comments
        fields = ['comment']

features/views.py
from django.shortcuts import render,reverse,redirect, get_object_or_404
from .forms import FeaturesForm
from .forms import CommentForm
from .models import Comments
from django.contrib.auth.decorators import login_required
from .models import Features, UpvoteFeature
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def all_features(request):
    features = Features.objects.all()
    return render(request, 'features.html', {'features': features})


def feature_detail(request, id):
    """Renders a view of an individual feature"""

    features = get_object_or_404(Features, id=id)
    
    upvotes = UpvoteFeature.objects.filter(upvoted_feature=features)
    
    upvoted = False
    user = str(request.user)
    for item in upvotes:
        item = str(item)
        if item == user:
            upvoted = True

    comments = Comments.objects.filter(feature_ticket=id).order_by('created_date')
    comments_number = comments.count()
    comment_form = CommentForm()
    features.views += 1
    features.save()

   
    return render(request, "feature_details.html", {'upvoted': upvoted,
                                                   'items': features,
                                                   'comment_form': comment_form,
                                                   'comments': comments,
                                                   'comments_number':comments_number})



@login_required
def add_comment_features(request, id=id):
    """Saves a posted comment  """

    feature = get_object_or_404(Features, id=id)
   

    comment_form = CommentForm(request.POST, request.FILES)
    if comment_form.is_valid():
        instance = comment_form.save(commit=False)
        instance.username = request.user
        instance.feature_ticket = feature
        
        comment_form.save()

    return redirect(feature_detail, id)



@login_required
def add_edit_feature(request, id=None):
    """Renders the add or edit page and saves features  """

    features = get_object_or_404(Features, id=id) if id else None
    user = str(request.user)
    add_edit = True
    if features == None:
        add_edit = False
    if request.method == "POST":
        form = FeaturesForm(request.POST, request.FILES, instance=features)
        
        if form.is_valid():
            form = form.save(commit=False)
        if user == 'admin' or user == 'testadmin':
                form.status = request.POST.get('status')  
                if str(form.status) == 'Doing':
                    form.waiting_date = None
                    form.in_progress_date = timezone.now()
                elif str(form.status) == 'Done':
                    form.in_progress_date = None
                    form.completion_date = timezone.now()
        if features == None:
                form.username = request.user
                form.views = -1
                form.created_date = timezone.now()
                form.waiting_date = timezone.now()
                form.save()
                return redirect(reverse(all_features))
                
        else:
                form.username = features.username 
                form.views -= 1
                form.save()
                return redirect(feature_detail, id)
      
    else:
        form = FeaturesForm(instance=features)
    return render(request, 'add_feature.html', {'add_edit': add_edit,
                                               'form': form})
                                               
"""                                              
@login_required
def upvote_feature(request):
    cart = request.session.get('cart', {})
    upvote_list = []

    for id,quantity in cart.items():
       feature = get_object_or_404(Features, pk=id)
       upvote_list.append(id)

    for id in upvote_list:
        feature_name = get_object_or_404(
            Features, id=id)
        try:
            upvote = get_object_or_404(
                UpvoteFeature, user=request.user, upvoted_feature=feature_name)
        except:
            upvote = UpvoteFeature()
        upvote.user = request.user
        upvote.upvoted_feature = feature_name
        feature_name.upvotes += 1
        feature_name.save()
        upvote.save()
    request.session['cart'] = {}
    return redirect(reverse('index'))               
    
"""
@login_required
def upvote_feature(request, id=id):
    """Adds one upvote point to the ticket  """
    feature = get_object_or_404(Features, id=id)
    feature.upvotes += 1
    feature.views -= 1
    feature.save()

    try:
        upvote = get_object_or_404(
            UpvoteFeature, upvoted_feature=feature, user=request.user)
    except:
       upvote = UpvoteFeature()
    upvote.upvoted_feature = feature
    upvote.user = request.user
    upvote.save()
    return(redirect(feature_detail, id))
    

features/templates/add_feature.html
{% extends 'base.html' %} {% load bootstrap_tags %} {% block content%}
<div class="container">
    <div class="page-container">
        <div class="content-wrap">
            <div class="center">
                <div class="row">
                    <div class="col-sm-12 col-md-10 col-md-offset-1 col-lg-offset-1">
                        {% if add_edit %}
                        <h1>Edit Feature</h1>
                        {% else %}
                        <h1>Add Feature</h1>
                        {% endif %}
                        <form enctype="multipart/form-data" method="post">
                            {% csrf_token %} {{ form | as_bootstrap}}
                             {% if user.username == 'admin' %}
                            <div id="div_id_status" class="form-group">
                                <label for="id_status" class="control-label required-field ">
                                Status
                                </label>
                                <div>
                                    <select name="status" class="form-control" id="id_status">
                        <option value="ToDo" selected>To Do</option>
                        <option value="Doing">Doing</option>
                        <option value="Done">Done</option>
                    </select>
                                </div>
                            </div>
                            {% endif %}
                            {% if add_edit %}
                            <button class="btn btn-primary" type='submit'>Edit <i class="fa fa-edit" aria-hidden="true"></i></button> {% else %}
                            <button class="btn btn-primary" type='submit'>Add <i class="fa fa-plus" aria-hidden="true"></i></button> {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% include 'footer.html' %}
    </div>
</div>
{% endblock %}

features/templates/feature_details.html
{% extends 'base.html' %} {% load static from staticfiles %} {% load bootstrap_tags %} {% block content%}

<div class="container center">
    <div class="page-container">
        <div class="content-wrap">
            <div class='inline '>
                <h1 class='section-details-h'>{{items.name}}</h1>
                <a class="btn btn-primary" href="{% url 'features' %}">Back</a>
                {% if user.username == 'admin' %}
                <a href="{% url 'edit_feature' items.id %}" class='btn btn-primary'>
            Edit <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        </a> {% endif %} 
        {% if user.is_authenticated %} 
        {% if items.id not in upvote_list %}
                <form class='inline' method="post" action="{% url 'add_to_cart' items.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="quantity" value="1">
                    
                    <button type='submit' class='btn btn-primary'>Add to Cart <i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
                </form>
                {% endif %}
                
                {% endif %}
                {% if upvoted %}
                <div class='btn btn-secondary'>Upvote Success!<i class="fa fa-smile-o" aria-hidden="true"></i></div>
                {% else %}
                <a class='btn btn-primary' href="{% url 'upvote_feature' items.id %}">Upvote <i class="fa fa-thumbs-up" aria-hidden="true"></i></a> {% endif %}
                <br>
                <p class='inline views text-shadow'><b>Views:</b> {{items.views}} </p>
                <p class='inline upvotes text-shadow'><b>Upvotes:</b> {{items.upvotes}}</p><br>
                <br>
                <p class=' inline section-text-b'>Status&#58;</p>
                {% if items.status == 'ToDo' %}
                <p class='inline status-todo'>{{ items.status }}</p>
                {% elif items.status == 'Doing' %}
                <p class='inline status-doing'>{{ items.status }}</p>
                {% elif items.status == 'Done' %}
                <p class='inline status-done'>{{ items.status }}</p>
                {% endif %}
            </div>
            <div class='center comments'>
                <div class="section-description inline">
                    <div>
                        <p class="creator-and-date inline"><b>{{items.username}}</b> {{items.created_date}}</p>
                        <p class='description inline'>{{items.description}}</p>
                    </div>
                </div>
            </div>
            <div class="comments ">
                <div class='margin-b-30'>
                    <h4 class='center'>Comments: ( {{ comments_number }} ) </h4>
                    <div class="short-line-white center"></div>
                </div>
                {% for comment in comments %}
                <div class="user-comment inline">
                    <div>
                        <p class="creator-and-date inline">
                            <b>{{comment.username}}</b> {{comment.created_date}}
                        </p>
                        <p class='description inline'>{{comment.comment}}</p>
                    </div>
                </div>
                {% endfor %}
                <div>
                    <form method="post" class="center" action="{% url 'add_comment_features' items.id %}">
                        {% csrf_token %}
                        <div id="div_id_comment" class="form-group  ">
                            <label for="id_comment" class="text-shadow control-label required-field ">
                        <h6>Add comment:</h6>
                    </label>
                            <div class="">
                                <textarea name="comment" cols="5" rows="4" class=" form-control" required="" id="id_comment"></textarea>
                            </div>
                        </div>
                        {% if user.is_authenticated %}
                        <button class="btn btn-primary inline" type="submit">Post</button> {% else %}
                        <div class="btn btn-primary inline">Post</div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        {% include 'footer.html' %}
    </div>
</div>
{% endblock %}}

features/templates/features.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <div class="page-container">
        <div class="content-wrap">
            <div class="form-display left">
                <form action="{% url 'search' %}" method="get">
                    <input class="input" type="text" name="q">
                    <button class="btn-search" type="submit">Search</button>
                    <a href="features.html"><button class="btn-search">Reset</button></a>
                </form>
            </div>
            <legend class="legend center">Features</legend>
            <div class="section-description center">
                <p class="section-text-b visible-lg visible-md visible-sm">If there is a Feature you would like to have developed, you can add that Feature to your cart </p>
                <p class="section-text-b visible-lg visible-md visible-sm">and checkout at a cost of €100 per upvote. We spend 50% of our time developing the most upvoted Feature</p>
                <p class="section-text-b visible-xs">If there is a Feature you would</p>
                <p class="section-text-b visible-xs">like to have developed you can add</p>
                <p class="section-text-b visible-xs">that Feature to your cart and checkout </p>
                <p class="section-text-b visible-xs">at a cost of €100 per upvote</p>
                <p class="section-text-b visible-xs">We spend 50% of our time developing</p>
                <p class="section-text-b visible-xs">the most upvoted Feature</p>
            </div>
            {% if user.is_authenticated %}
            <div class='center'>
                <a class='btn btn-primary add-section-btn' href="{% url 'add_feature' %}"><i class="fa fa-plus"></i> Add
            Feature</a>
            </div>
            {% endif %}
            <div class="row row-flex">
                {% for feature in features %}
                <div class="col-xs-12 col-xs-offset-1 col-sm-offset-0 col-sm-5 col-md-3 col-lg-3  display panel panel-default center">
                    <div class="panel-body">
                        {% if feature.status == 'ToDo' %}
                        <p class='red circle'></p>
                        {% elif feature.status == 'Doing' %}
                        <p class='orange circle'></p>
                        {% elif feature.status == 'Done' %}
                        <p class='green circle'></p>
                        {% endif %}
                        <h4 class="section-text-b">{{feature.name }}</h4>
                        <p class=' inline section-text-b'>Status&#58;</p>
                        {% if feature.status == 'ToDo' %}
                        <p class='inline status-todo'>{{ feature.status }}</p>
                        {% elif feature.status == 'Doing' %}
                        <p class='inline status-doing'>{{ feature.status }}</p>
                        {% elif feature.status == 'Done' %}
                        <p class='inline status-done'>{{ feature.status }}</p>
                        {% endif %}
                        <p>Issued&#58;{{ feature.created_date }}</p>
                        <p>{{feature.description }}</p>
                        <form method='get' class='inline' action="{% url 'feature_detail' feature.id %}">
                            <div class=''>
                                <button type='submit' class=' btn btn-primary inline'>View Feature </button>
                            </div>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% include 'footer.html' %}
    </div>
</div>
{% endblock %}